apiVersion: v1
kind: Service
metadata:
  name: argo-cd-argocd-server
  namespace: production
spec:
  type: ExternalName
  externalName: argo-cd-argocd-server.argo.svc.cluster.local  # Reference the ArgoCD service in the 'argo' namespace
  ports:
    - port: 80
      targetPort: 8081  # Default ArgoCD server port
