apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: production
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: lavi324/public1-backend:2.1
          ports:
            - containerPort: 3001
          env:
            - name: MONGO_URI
              value: mongodb://root:8k5WXVSQoY@mongodb.mongo.svc.cluster.local:27017/?authSource=admin
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: production
spec:
  selector:
    app: backend
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
  type: LoadBalancer

